project: 
  type: website


website:
  title: "Latex Finance Formulas"
  favicon: Images/favicon.png
  back-to-top-navigation: true


  navbar:
    background: primary
    search: true
    right:
      - text: "Home"
        file: index.qmd
      - text: "Formulas"
        file: formulas.qmd

  sidebar:
    - title: "Render Docs"
      style: "docked"
      background: light
      contents:
        - text: "Formulas Render"
          file: formulas.qmd
        - text: "Rates and Returns"
          file: quant_rates_returns.qmd

format:  
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



