project: 
  type: website


website:
  title: "Latex Finance Formulas"
  favicon: Images/favicon.png
  back-to-top-navigation: true


  navbar:
    background: primary
    search: true
    right: # controls if navbar is left or right side of page
      - text: "Home"
        file: index.qmd
      - text: "Formulas"
        file: formulas.qmd
      - sidebar:quant_methods

  sidebar:
    - title: "Render Docs"
      style: "docked"
      background: light
      contents:
        - text: "Formulas Render"
          file: formulas.qmd


    - id: quant_methods
      title: Quantitative Methods
      style: "docked"
      collapse-level: 1
      contents:
        - section: "Overview"
          contents:
            - quant/time_value.qmd
            - quant/rates_return.qmd

format:  
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



